---
Google:
 - Google: https://encrypted.google.com/
 - Blogs: https://www.google.com/blogsearch
 - Docs: http://docs.google.com/
 - Drive: https://drive.google.com/
 - Finance: https://www.google.com/finance
 - Flights: http://www.google.com/flights/
 - Gmail: http://mail.google.com
 - Hotels: http://www.google.com/hotelfinder/
 - Images: https://encrypted.google.com/imghp
 - Maps: https://maps.google.com/
 - News: https://www.google.com/news
 - Plus: https://plus.google.com/
 - Shopping: http://www.google.com/shopping
 - Translate: http://translate.google.com/
 - Trends: https://www.google.com/trends/
 - Video: http://www.google.com/videohp
 - Voice: https://www.google.com/voice

Api:
 - Convert Api: http://www.convertapi.com/
 
Banking:
 - Bitcoin: http://bitcoin.org/
 - Bitinstant: https://www.bitinstant.com/
 - Chase: https://www.chase.com/
 - Citibank: http://www.citibank.com
 - Coinbase: https://coinbase.com/
 - Dwolla: http://www.dwolla.com/
 - Etrade: https://us.etrade.com/home
 - Internet Credit Union: https://iafcu.org/
 - Liberty Reserve: http://www.libertyreserve.com/
 - Moneygram: https://www.moneygram.com
 - Morningstar: http://www.morningstar.com/
 - Mt Gox: https://mtgox.com/
 - Paypal: https://www.paypal.com/
 - Quizzle: https://www.quizzle.com/
 - Square: https://squareup.com/
 - Stripe: https://stripe.com/
 - Vanguard: https://investor.vanguard.com/home/
 - Wells Fargo: https://www.wellsfargo.com/
 - WesternUnion: http://www.westernunion.com/
 - Mint: https://www.mint.com/
 
Bitcoin:
 - Local Bitcoins: https://localbitcoins.com/
 - Market Data: http://bitcoin.clarkmoody.com/
 - Coin Market Capitalizations: http://coinmarketcap.com/
 - Bitcoin Market: http://bitcoinity.org/markets
 - Bitaddress: https://www.bitaddress.org
 - Coin List: http://www.thecoinlist.com/
 
Blogs:
 - Hackaday: http://hackaday.com/
 - ITS Tactical: http://www.itstactical.com/
 - Lifehacker: http://blog.lifehacker.com/
 - Prepper Journal: http://www.theprepperjournal.com/
 - Stormdrane: http://stormdrane.blogspot.com/
 - Teotwawki: http://teotwawkiblog.blogspot.co.uk/
 - Low End Box: http://lowendbox.com/
 
Cloud Storage:
 - Adrive: http://www.adrive.com/
 - Box: https://www.box.com/
 - Dropbox: https://www.dropbox.com/
 - Evernote: https://evernote.com/
 - Github: https://github.com/
 - Pastebin: http://pastebin.com/
 - Skydrive: https://skydrive.live.com/
 - Owncloud: http://owncloud.org/
 - Wuala: https://www.wuala.com/
 
Databases:
 - CVE Details: http://www.cvedetails.com/
 - Exploit Database: http://www.exploit-db.com/
 - Google Hacking Database: http://www.hackersforcharity.org/ghdb/
 - GoogleDorks: http://www.exploit-db.com/google-dorks/
 - SecurityFocus: http://www.securityfocus.com/
 - Shellcode Database: http://www.shell-storm.org/shellcode/
 - Vulnerability Database: http://osvdb.org/
 - WineDB: http://appdb.winehq.org/
 - Leaks: http://www.leaksdb.org/
 - LeakedIn: http://www.leakedin.com/
 - Dbpedia: http://dbpedia.org/
 - Integer Sequences: http://oeis.org/
 - 5000 Best: http://5000best.com/
 - Data Loss: http://datalossdb.org/
 - Radio Reference: http://www.radioreference.com/
 
Editors:
 - Notex: https://notex.ch/
 - Restructured Text: http://rst.ninjs.org/
 
Fonts:
 - WhatTheFont: http://www.myfonts.com/WhatTheFont/
 
Footprinting:
 - Alexa: http://www.alexa.com/
 - Arin: https://www.arin.net/
 - Built With: http://builtwith.com/
 - Bulk IP Address Location: http://www.ipligence.com/iplocation
 - Dns Tools: http://www.dnsstuff.com/tools
 - Domain Dossier: http://centralops.net/co/
 - Domain Tools: http://www.domaintools.com/
 - Glass Door: http://www.glassdoor.com/index.htm
 - Hacking Tools: http://www.phaster.com/find_info_net_traffic.shtml
 - IP Address Tracer: http://www.ip-adress.com/ip_tracer
 - IP Neighbors: http://www.my-ip-neighbors.com/
 - Netcraft: http://news.netcraft.com/
 - Recorded Future: https://www.recordedfuture.com/live/
 - Reverse Whois: http://www.ewhois.com/
 - Ripe: https://apps.db.ripe.net/search/query.html
 - Server Sniff: http://serversniff.net/index.php
 - Shodan: http://www.shodanhq.com/
 - SSL Server Test: https://www.ssllabs.com/ssltest/index.html
 - Tcpiputils: http://www.tcpiputils.com/
 - Testing: www.jonasjohn.de/test-tool
 - You Get Signal: http://www.yougetsignal.com/
 
Forums:
 - 4chan: http://www.4chan.org/
 - AntiOnline: http://www.antionline.com/
 - Binary Revolution: http://www.binrev.com/forums/
 - Every Day Carry: http://www.edcforums.com/forum/
 - Government Security: http://www.governmentsecurity.org/forum/
 - HackThisSite: http://www.hackthissite.org/forums/index.php
 - Hak5: http://forums.hak5.org/
 - Kali: http://forums.kali.org/forum.php
 - Reddit: http://www.reddit.com/
 - SecurityOverride: http://securityoverride.org/forum/index.php
 - Stack Overflow: http://stackoverflow.com/
 - Survival Cache: http://www.survivalcache.com/forums/forum.php
 - Ubuntu: http://ubuntuforums.org/
 - Urban Exploration: http://www.uer.ca/
 - Ycombinator: http://news.ycombinator.com
 - Zombie Squad: http://www.zombiehunters.org/forum/
 - Talk Gold: http://www.talkgold.com/forum/
 
Knowledge:
 - Linux Information: http://www.linfo.org/
 - Password Research: http://www.passwordresearch.com/index.html
 - Khan Academy: https://www.khanacademy.org/
 
Maps:
 - Area Code Maps: http://www.allareacodes.com/area-code-map.htm
 - Bing Maps: http://www.bing.com/maps/#CloseTaskArea
 - Cia Factbook: https://www.cia.gov/library/publications/the-world-factbook/index.html
 - Jiwire: http://v4.jiwire.com/search-hotspot-locations.htm
 - Mapquest: http://www.mapquest.com/satellite-maps/
 - TerraServer: http://www.terraserver.com/
 - Wifi: https://wigle.net/gps/gps/Map/onlinemap2/
 - Wikivoyage: http://en.wikivoyage.org/wiki/Main_Page
 - Zip Code Maps: http://www.usnaviguide.com/zip.htm
 - Zillow: http://www.zillow.com
 - Trulia: http://www.trulia.com
 - Roadtrip: https://roadtrippers.com/
 - Neighbors: http://neighbors.whitepages.com/
 - Waymarking: http://www.waymarking.com/
 - Spot Crime: http://www.spotcrime.com/
 - Falling Fruit: http://fallingfruit.org/
 - Geocaching: http://www.geocaching.com/
 
Media:
 - Camera Finder: http://www.stolencamerafinder.com/
 - Dailymotion: http://www.dailymotion.com/us
 - DeviantArt: http://www.deviantart.com/
 - Exif Viewer: http://regex.info/exif.cgi
 - Filecrop: http://www.filecrop.com/
 - Flickr: https://secure.flickr.com/
 - Keepvid: http://keepvid.com/
 - Picgeni: http://www.picgeni.com/
 - Security Tube: http://www.securitytube.net/
 - Tineye: https://www.tineye.com/
 - Youtube: https://www.youtube.com/
 - Imgur: https://imgur.com/
 
Medical:
 - Drugs: http://www.drugs.com/
 - Nutrition Data: http://nutritiondata.self.com/
 
Nature:
 - Botany: http://www.botany.com/
 - Plant Identifier: http://plant-id.novenyhatarozo.info/Identifier
 
Network Tools:
 - W3dt: https://w3dt.net/
 
News:
 - BBC: http://www.bbc.co.uk/news/world/
 - CNN: http://www.cnn.com/
 - Digg: http://www.digg.com/
 - Huffington Post: http://www.huffingtonpost.com
 - Newsmap: http://newsmap.jp/
 - NHK: http://www3.nhk.or.jp/nhkworld/
 - Weatherbug: http://weather.weatherbug.com/
 
Parsers:
 - Explain Shell: http://explainshell.com/
 - Linux Commands Examples: http://linux-commands-examples.com/
 
Password Cracking:
 - Collision: http://www.c0llision.net/webcrack.php
 - Crackstation: http://crackstation.net/
 - Md5Crack: http://www.md5crack.com/
 - Md5Decrypter: http://www.md5decrypter.co.uk/
 
Payment:
 - Ripple: https://ripple.com/
 
Pentesting:
 - Bookmarks: https://code.google.com/p/pentest-bookmarks/wiki/BookmarksList
 - CSO: http://www.csoonline.com/
 - Pentest Standard: http://www.pentest-standard.org/index.php/Main_Page
 - Nessus: http://www.tenable.com/products/nessus
 - Rapid7: http://www.rapid7.com/
 - Vulnerability Assessment: http://www.vulnerabilityassessment.co.uk/Penetration%20Test.html
 - Wifi Pineapple: http://cloud.wifipineapple.com/
 - Ikat: http://ha.cked.net/
 
Pentesting Blogs:
 - CarnalOwnage: http://carnal0wnage.attackresearch.com/
 - Corelan: https://www.corelan.be/
 - Darknet: http://www.darknet.org.uk/
 - Digininja: http://www.digininja.org/blog.php
 - Irongeek: http://www.irongeek.com/
 - Kali: http://www.kali.org/blog/
 - Maltego: http://maltego.blogspot.com/
 - Metasploit: https://community.rapid7.com/community/metasploit/blog
 - Pentest Geek: http://www.pentestgeek.com/
 - Redteams: http://redteams.net/
 - Sensepost: http://www.sensepost.com/blog/
 - Social Engineering: http://www.social-engineer.org/blog/
 - TrustedSec: https://www.trustedsec.com/news-and-events/
 - Exploit Monday: http://www.exploit-monday.com/
 - Tek Defense: http://www.tekdefense.com/
 
People Search:
 - 123People: http://www.123people.com/
 - Ancestry: http://www.ancestry.com/
 - BeenVerified: http://www.beenverified.com/
 - Jigsaw: http://www.jigsaw.com/
 - NetR Online: http://publicrecords.netronline.com/
 - NewUltimates: http://www.newultimates.com/
 - Peekyou: http://www.peekyou.com/
 - People Finders: http://www.peoplefinders.com/
 - PeopleSmart: http://www.peoplesmart.com/
 - Pipl: https://pipl.com/
 - Public Records: http://publicrecords.searchsystems.net/
 - Radaris: http://radaris.com/
 - Searchbug: http://www.searchbug.com/
 - Skipease: http://skipease.com/
 - Spokeo: http://www.spokeo.com/
 - Virtual Gumshoe: https://www.virtualgumshoe.com/resources/
 - White Pages: http://www.whitepages.com/
 - Wink: http://wink.com/
 - Zaba Search: http://www.zabasearch.com/
 - Zoominfo: http://www.zoominfo.com/
 
Programming Reference:
 - Boost: http://www.boost.org/doc/libs/
 - Cheatsheets: http://www.cheat-sheets.org/
 - C++: http://www.cplusplus.com/reference/
 - Java: http://docs.oracle.com/javase/6/docs/
 - Language Comparisons: http://hyperpolyglot.org/
 - Matplotlib: http://matplotlib.org/contents.html
 - Python: http://www.python.org/doc/
 - Qt: http://doc.qt.digia.com/
 - Ruby: http://ruby-doc.org/
 - Sqlite: https://www.sqlite.org/docs.html
 - Windows API: http://msdn.microsoft.com/en-us/library/windows/desktop/hh447209(v=vs.85).aspx
 - wxPython: http://wiki.wxpython.org/
 
Questions:
 - Stack Overflow: https://stackoverflow.com/
 - Super User: https://superuser.com/
 - Server Fault: https://serverfault.com/
 - Yahoo Answers: http://answers.yahoo.com/
 
Regex:
 - Regex101: http://regex101.com/
 - Rubular: http://rubular.com/
 - Regular Expression Analyzer: http://www.myezapp.com/apps/dev/regexp/show.ws
 - RegexLib: http://regexlib.com/
 
Reviews:
 - Yelp: http://www.yelp.com/
 - Glassdoor: http://www.glassdoor.com/
 - Better Business Bureau: http://www.bbb.org/
 
Scripts:
 - Command Line Fu: http://www.commandlinefu.com/commands/browse
 - Shell Fu: http://www.shell-fu.org/
 - Pentesting Scripts: http://www.pentesterscripting.com/
 
Search:
 - Addictomatic: http://addictomatic.com/
 - Bing: http://www.bing.com
 - Duck Duck Go: https://duckduckgo.com/
 - IxQuick: https://ixquick.com/
 - Metacrawler: http://www.metacrawler.com/
 - Rss: http://www.rsssearchhub.com/
 - Search.com: http://www.search.com/
 - Wayback Machine: http://archive.org/web/web.php
 - Wikia: http://www.wikia.com/Wikia
 - Wikipedia: https://en.wikipedia.org/wiki/Main_Page
 - Wolfram Alpha: https://www.wolframalpha.com/
 - Yahoo: http://www.yahoo.com
 - Pastebin Search: https://www.google.com/cse/home?cx=016532440259489736171:xdorrqdrvv0
 - Runnable: http://runnable.com/
 - Nerdy Data: https://search.nerdydata.com
 - Sencept: http://www.sencept.com/
 - Million Short: https://millionshort.com/index.html
 
Security Forums:
 - InsidePro: http://forum.insidepro.com/
 
Security News:
 - DarkReading: http://www.darkreading.com/
 - PacketStorm: http://packetstormsecurity.com/news/
 - Infosec Island: http://infosecisland.com/
 - Hacker News: http://thehackernews.com/
 - Cyber War News: http://www.cyberwarnews.info/
 - Nova Infosec: https://www.novainfosec.com/
 
Services:
 - Crashplan: http://www.crashplan.com/
 - IFTTT: https://ifttt.com/
 - Lastpass: https://lastpass.com/
 - Namecheap: https://www.namecheap.com/
 - Prey: http://preyproject.com/
 - Rss: http://fulltextrssfeed.com/
 - Yahoo Pipes: http://pipes.yahoo.com/pipes/
 - Mailstrom: https://mailstrom.co/
 - Visualping: http://visualping.io/
 - Backupsy: http://backupsy.com/
 - Dreamhost: http://www.dreamhost.com/
 - Amazon Web Services: https://aws.amazon.com/free/
 
Shopping:
 - 511 Tactical: http://www.511tactical.com/
 - Ace Hackware: http://acehackware.com/
 - Amazon: http://www.amazon.com/
 - Camel: http://camelcamelcamel.com/
 - Craigslist: http://www.craigslist.org
 - Ebay: http://www.ebay.com/
 - LockPick Shop: http://www.lockpickshop.com/
 - Minimus: http://www.minimus.biz/
 - Newegg: http://www.newegg.com/
 - TigerDirect: http://www.tigerdirect.com
 - Vigilant Gear: http://www.vigilantgear.com/
 - Overstock: http://www.overstock.com/
 
Similar:
 - More Of It: http://www.moreofit.com/
 
Social Engineering:
 - Business Card Generator: http://namegenerator.in/
 - Credit Card Generator: http://www.getcreditcardnumbers.com/
 - Fake Mail Generator: http://www.fakemailgenerator.com/
 - Fake Name Generator: http://www.fakenamegenerator.com/
 - Identity Generator: http://www.identitygenerator.com/
 - Social Security Number Generator: http://www.fakenamegenerator.com/social-security-number.php
 
Social Media:
 - Facebook: https://www.facebook.com/
 - IRC: http://searchirc.com/
 - Linkedin: http://www.linkedin.com/
 - Myspace: https://www.myspace.com/
 - Pinterest: http://www.pinterest.com/popular
 - Twitter: https://twitter.com/
 - Tumblr: http://www.tumblr.com
 - Instagram: http://instagram.com/
 - Foursquare: https://foursquare.com/
 - Meetup: http://www.meetup.com/
 - Wamble: http://wamble.co/
 
Social News:
 - Reddit: http://us.reddit.com
 
Tech News:
 - ArsTechnica: http://arstechnica.com/
 - Engadget: http://www.engadget.com/
 - Gizmodo: http://blog.gizmodo.com/
 - The Verge: http://www.theverge.com/
 - Wired: http://www.wired.com/
 - Tech In Asia: http://www.techinasia.com/
 
Tools:
 - Chrome Extension Downloader: http://chrome-extension-downloader.com/
 - Identifont: http://www.identifont.com/
 - Ideone: http://ideone.com/
 - Json Parser: http://json.parser.online.fr/
 - Regexpal: http://regexpal.com/
 - Repl.it: http://repl.it/
 - Restructured Text: http://rst.ninjs.org/
 - Ruby: http://joshnuss.github.io/mruby-web-irb/
 - Shapecatcher: http://shapecatcher.com/
 - Sql Fiddle: http://sqlfiddle.com/
 - Txt2re: http://txt2re.com/
 - Yaml Parser: https://yaml-online-parser.appspot.com/
 - Just Delete Me: http://justdelete.me/
 - Page2Rss: http://page2rss.com/
 
Torrents:
 - Pirate Bay: https://thepiratebay.se/
 - Kickass Torrents: http://kickass.to/
 
Travel:
 - AirBnB: https://www.airbnb.com
 - Couch Surfing: https://www.couchsurfing.org/
 - Fly or Drive Calculator: http://www.befrugal.com/tools/fly-or-drive-calculator/
 - Hipmunk: http://www.hipmunk.com/
 - Hotwire: https://www.hotwire.com/
 - Kayak: http://www.kayak.com/
 - Momondo: http://www.momondo.com/
 - Priceline: http://www.priceline.com/
 - Skyscanner: http://www.skyscanner.com/
 - Travelocity: http://www.travelocity.com/
 - TripIt: https://www.tripit.com
 - Cruise Sheet: http://cruisesheet.com/
 
User Search:
 - Checkusernames: http://checkusernames.com/
 - Knowem: http://knowem.com/
 - Namechk: http://namechk.com/
 - SimplyMeasured: http://simplymeasured.com/free-social-media-tools
 - Social Mention: http://socialmention.com/
 - Tweepz: http://tweepz.com/
 - YoName: http://www.yoname.com/
 - Have I been Pwned: https://haveibeenpwned.com/
 
Webcams:
 - Biglook: http://www.webcambiglook.com/index.htm
 - Earthcam: http://www.earthcam.com/mapsearch/
 - Heycam: http://www.heycam.com/
 - Opentopia: http://www.opentopia.com/map.php
 - TrafficLand: http://trafficland.com/mapnav.jsp
 - WeatherUnderground: http://www.wunderground.com/webcams/
 - WeatherUsa: http://www.weatherusa.net/skycamnet/
 - WebcamLocator.com: http://www.webcamlocator.com/
 - WebcamLocator.net: http://webcamlocator.net/find-webcams-using-google/
 - Webcampedia: http://www.webcampedia.com/locations.php
 - WebcamsTravel: http://www.webcams.travel/map/
 - WXnation: http://www.wxnation.com/webcams.html
 
Wikis:
 - The Password Project: http://thepasswordproject.com/
 - Skull Security: https://wiki.skullsecurity.org/index.php?title=Main_Page
 
Words:
 - Words For That: http://www.wordsforthat.com/
...
